# Generated by Django 4.2.1 on 2023-05-31 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roommessagemodel',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='roomroommodel',
            options={'ordering': ['date_created']},
        ),
    ]
