# Generated by Django 4.2.1 on 2023-06-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_roommessagemodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessagemodel',
            name='media_file',
            field=models.FileField(blank=True, upload_to='room_media'),
        ),
    ]
